# Generated by Django 3.0.7 on 2020-06-28 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Activities', '0002_auto_20200627_2008'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
    ]
